### ISSUE TITLE
ARTOOLS can't use buildiso to build any DE

### ISSUE THREAD

**Issue by robin0800** [artix-linux/world#39]
Please add "artix-iso-profiles" to pkgbuild and amend any build scripts needed to allow buildiso to build a DE 
see https://forum.artixlinux.org/index.php/topic,246.0.html

**Comment by robin0800** [comment]
@udev if you know how to make it build a DE iso please tell or if its designed to only make a base install please say so?

**Comment by DamnWidget** [comment]
@udeved marked this as invalid because this ticket title and description is invalid, there is no problem with buildiso, but you don't know how to properly use it.

I don't think buildiso is something that users are supposed to be using by themselves there is little to no value in create an ISO with cinnamon as you can just install it from base or any other of the ISOs just login into the installed system and using `pacman` regularly.

**Comment by udeved** [comment]
@robin0800 

Your assumption tzhat buildiso is broke is wrong, works fine.
It just does not work like on manjaro any longer, and I have not yet documented it for artix.
iso-profiles lost importance on artix, since we went netinstall. 
The "new" iso profiles is the netgroups, and any iso  with a DE only serves as a base to run calamares, or to use a recovery disk.

**Comment by robin0800** [comment]
Thanks to both of you above for your comments I know about the netgroups and have written how to use them see  https://forum.artixlinux.org/index.php/topic,30.0.html 
If you don't want artools used why not remove them from world/master

**Comment by DamnWidget** [comment]
We never said that **we dot want them to be used** by users, I just said that they are not intended for a general public (with what that implies, fast changes, no version compatibility, bugs, and no documentation).

By the way, we developers are also users, and we also use `pacman` so we need those tools in the repos.

Regards.

**Comment by robin0800** [comment]
My last comment it would be nice if buildiso could if say this command "buildiso -p base" would build the base or net install and "buildiso -p cinnamon would build base+cinnamon.
obviously substitute any other DE included in artix-iso-profiles for cinnamnon

**Comment by udeved** [comment]
It does that, your buildiso si simply not properly configured to read profiles other than base.
