### ISSUE TITLE
Build packages with debug symbols?

### ISSUE THREAD

**Issue by physkets** [artix-linux/world#53]
Why do Arch packages have no debug symbols? Is it because it increases package sizes, or compile time, or something like that?

I was wondering if we could do it differently, because I very often encounter this problem, where I provide backtraces to devs, and they tell me that it doesn't have enough information due to missing debug symbols. This has happened a lot when I report KDE/Plasma crashes.

https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces

**Comment by thefallenrat** [comment]
> Why do Arch packages have no debug symbols? Is it because it increases package sizes, or compile time, or something like that?

Because we don't want unnecessary modifications
https://wiki.archlinux.org/index.php/Arch_Linux#Simplicity

> I was wondering if we could do it differently, because I very often encounter this problem, where I provide backtraces to devs, and they tell me that it doesn't have enough information due to missing debug symbols. This has happened a lot when I report KDE/Plasma crashes.

Then do what the devs told you by rebuilding the package with debug symbols (You can use upstream PKGBUILDs to do that) instead asking us to do so for you

Use the link you provided yourself to get started rebuilding

Closing..

**Comment by udeved** [comment]
Simply not viable for us, requires tons of modifications to packages.
If we wanted that, we would have to do it properly by having split out debug symbol packages.
Unless arch start to add debug packages, consider this way out of reach for us in terms of workforce.
